# Generated by Django 4.2 on 2023-04-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='cart_id',
        ),
    ]
