# Generated by Django 4.2 on 2023-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_product'),
        ('carts', '0009_alter_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='store.variation'),
        ),
    ]
