# Generated by Django 4.2 on 2023-05-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../../media/userprofile/avat.jpg', null=True, upload_to='userprofile'),
        ),
    ]
